###
POST http://localhost:4004/odata/v4/lego-shop/AddToCart HTTP/1.1
Content-Type: application/json

{
    "productId": "9f1c2b9a-bb3a-4b6b-87f1-42b3e5c87913",
    "userId": "user1",
    "quantity": 1
}
###

###
GET http://localhost:4004/odata/v4/lego-shop/ShoppingCart?$filter=userId eq 'user1' HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:4004/odata/v4/lego-shop/ShoppingCart(0a63c860-5a1c-4b5a-a774-d70ef23e3fcc) HTTP/1.1
Content-Type: application/json

##################################

###
POST http://localhost:4004/odata/v4/lego-shop/ApplyPromo
Content-Type: application/json

{
    "shoppingCartId": "047871cc-93c8-41f5-b003-7306260ed850",
    "promoCode": "SUMMER10"
}